apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
data:
  embedEtcd.yaml: |
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://0.0.0.0:2379
    quota-backend-bytes: 4294967296
    auto-compaction-mode: revision
    auto-compaction-retention: '1000'
  user.yaml: |
    # Extra config to override default milvus.yaml

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.6.0
          args: ["milvus", "run", "standalone"]
          ports:
            - containerPort: 19530
            - containerPort: 9091
            - containerPort: 2379
          env:
            - name: ETCD_USE_EMBED
              value: "true"
            - name: ETCD_DATA_DIR
              value: "/var/lib/milvus/etcd"
            - name: ETCD_CONFIG_PATH
              value: "/milvus/configs/embedEtcd.yaml"
            - name: COMMON_STORAGETYPE
              value: "local"
            - name: DEPLOY_MODE
              value: "STANDALONE"
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
            - name: milvus-config
              mountPath: /milvus/configs/embedEtcd.yaml
              subPath: embedEtcd.yaml
            - name: milvus-config
              mountPath: /milvus/configs/user.yaml
              subPath: user.yaml
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: milvus-data
          persistentVolumeClaim:
            claimName: milvus-data
        - name: milvus-config
          configMap:
            name: milvus-config

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
spec:
  selector:
    app: milvus
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
    - name: metrics
      port: 9091
      targetPort: 9091
    - name: etcd
      port: 2379
      targetPort: 2379
  type: ClusterIP
---
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: milvus-health
spec:
  to:
    kind: Service
    name: milvus-service
  port:
    targetPort: metrics
  tls:
    termination: edge
---
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: milvus-grpc
spec:
  to:
    kind: Service
    name: milvus-service
  port:
    targetPort: grpc
  tls:
    termination: passthrough
